spring.application.name=OptionScanner

spring.datasource.url=jdbc:postgresql://localhost:5432/optionscanner
spring.datasource.username=postgres
spring.datasource.password=bondstone

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.com.larrydevincarter.optionscanner=DEBUG
#switch back to INFO
logging.level.org.hibernate=ERROR

alpaca.api.key=PKLATQLWLVKTC4LASY2E
alpaca.api.secret=8sKg8ymUNUtYtbTiI4i1WgFvcegYTgeJ1o5zasYR
alpaca.api.base-url=https://paper-api.alpaca.markets

alphavantage.api.key=NVMW9E4MHJ4RTGQQ
alphavantage.api.base-url=https://www.alphavantage.co

revenue.growth.cagr.threshold=5.0
revenue.growth.years=5
revenue.growth.filter.enabled=true